Fix #333: Change exported GPX filenames to 'YYYY-MM-DD_hh-mm-ss_OSMTracker.gpx'
labexp/osmtracker-android pull request #482
Opened 2024-12-09 14:15 UTC by Kevin-Salazar-itcr

* This PR fixes the issue #333 

Update GPX export filenames to follow the format YYYY-MM-DD_hh-mm-ss_OSMTracker.gpx for better organization and clarity.

2024-12-09 16:54 UTC, jer194 commented
Does it also address https://github.com/labexp/osmtracker-android/issues/470 ?
I.e.: preset could be 'OSMTracker', but it can be changed to any user specified string?

2024-12-09 17:19 UTC, Kevin-Salazar-itcr commented
Hi @jer194, yes it does, since Binette commented it's a duplicated of #333.

This solution simply takes the track name and appends "_OSMTracker" label to the end. Allowing users to provide a custom label is a feature that could be implemented later.

2024-12-10 08:16 UTC, Binnette commented
Hi @Kevin-Salazar-itcr thank a lot for this PR! Feel free to review other bugs that I tagged as "[Good first issue](https://github.com/labexp/osmtracker-android/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)". Others PR will be more than welcome 👍

@jer194, since you are interested by this bug, feel free to try the APK with this fix. You can find the "zip artifact" containing the APK at the bottom of this page: https://github.com/labexp/osmtracker-android/actions/runs/12237475785?pr=482

Once tested, I will merge this PR as the code changes looks good to me.

2024-12-10 11:37 UTC, jer194 commented
Hi both, 
the provided apk does not include the change in the PR from #483,
that's what I am really after :-)
Thanks - Jakob.

2024-12-10 17:32 UTC, Binnette requested changes
Hi @Kevin-Salazar-itcr You changed the code of ExportToTempFileTask, but this code is only used to export a track in a temp folder before sending the track to OpenStreetMap. So you need to check code of ExportToStorageTask

Also, as of today, when I export a track, I get:
- A folder `2024-12-10_12-24-58` (this is OK)
  - My GPX file `2024-12-10_12-24-58_2024-12-10_12-24-58.gpx` (this needs to be changed

Can you please try to change this. And test it via the App. Long click on a track > Export as GPX. The track is exported in Document folder > osmtracker

2024-12-10 23:15 UTC, Andyporras commented
HI @Binnette, to me personally if it works well, the trace that I share shares it with the name: 2024-12-08_07-02-33_OSMTracker.gpx

2024-12-10 23:30 UTC, Andyporras commented
Hi @Binnette, and if you make a function that contains the change that @Kevin-Salazar-itcr  made, since at the time of modifying this function also alters the operation of export as gpx and upload to OpenStreetMap, then would not it be good to make a separate function to share?

2024-12-16 21:34 UTC, Binnette commented
I close this PR. See #483 for more details.

2024-12-16 21:34 UTC, closed without merging